# Generated by Django 6.0.1 on 2026-03-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerproducts', '0003_remove_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, help_text='Optional secondary image shown on hover', null=True, upload_to='flowerproducts/'),
        ),
    ]
