from django.shortcuts import render

# Create your views here.
def add_to_cart(request): ...
def checkout_start(request): ...
def checkout_success(request): ...
def checkout_cancel(request): ...
def order_strip_webhook(request): ...