# Generated by Django 6.0.1 on 2026-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_checkout_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="country",
            field=models.CharField(blank=True, default="CA", max_length=2),
        ),
    ]
