# Generated by Django 6.0.1 on 2026-03-01 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_country_default_ca"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="state",
            new_name="province",
        ),
    ]
