# Generated by Django 6.0.1 on 2026-03-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_state_to_province"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="is_admin",
            new_name="is_staff",
        ),
        migrations.AlterField(
            model_name="account",
            name="full_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
