# Generated by Django 6.0.1 on 2026-02-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("OFF_TOPIC", "Off-topic"),
                            ("INAPPROPRIATE", "Inappropriate"),
                            ("Fake", "Fake"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("review", "email"),
                        name="unique_flag_per_review_per_email",
                    )
                ],
            },
        ),
    ]
