# Generated by Django 6.0.1 on 2026-02-11 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_remove_flag_created_at_alter_flag_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
