# Generated by Django 6.0.1 on 2026-02-28 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0006_flag_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("email", "review")},
        ),
    ]
