# Generated by Django 6.0.1 on 2026-03-04 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_add_category_image"),
        ("reviews", "0007_alter_vote_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="flag",
            name="unique_flag_per_review_per_email",
        ),
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_review_per_product_per_email",
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "review")},
        ),
        migrations.AddConstraint(
            model_name="flag",
            constraint=models.UniqueConstraint(
                fields=("review", "user"), name="unique_flag_per_review_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("product", "user"), name="unique_review_per_product_per_user"
            ),
        ),
    ]
