# Generated by Django 6.0.1 on 2026-04-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_comment_options_alter_vote_unique_together_and_more'),
        ('reviews', '0008_remove_flag_unique_flag_per_review_per_email_and_more'),
    ]

    operations = [
    ]
