# Generated by Django 6.0.1 on 2026-02-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_add_category_image"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique_order_item"
            ),
        ),
    ]
