# Generated by Django 6.0.1 on 2026-03-05 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
