# Generated by Django 6.0.1 on 2026-03-06 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_wishlistitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistitem",
            name="quantity",
        ),
    ]
