# Generated by Django 6.0.1 on 2026-01-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
