# Generated by Django 6.0.1 on 2026-02-11 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_views_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="views_count",
        ),
    ]
